### ISSUE TITLE
Question about kraken report

### ISSUE THREAD

**Issue by mbpincus** [IBS574/metagenome_assignment#1]
Hello,

I'm having trouble with outputting the kraken report. I first ran the line of code where I specified the fastq files I want, that ran for a few minutes and seemed fine. Then I ran the line of code that begins with kraken-report and started it yesterday and it's still hanging. An empty file named kraken_report was created. I'm not sure if I did something wrong or how to even diagnose the problem. At the moment, I deleted the empty kraken_report and am re-running the command.
On a related question, I don't understand how the command line for the kraken-report creates a report specific for the fastq files you are using since you don't reference them in the command line?

Thanks,
Melanie

**Comment by plasmid02** [comment]
Sorry about that, the instructions were wrong and hopefully I fixed them.
1.  When running kraken the zipped fastq files should be entered after all the options. 
2.  yes, the kraken out file needs to be in the kraken-report statement.

I checked the new version and it works for me
